### PR TITLE
Prevent creating duplicate pages with modal

### PR DESCRIPTION
**Pull request by briaguya**
This simply hides the modal while we're waiting to redirect to the newly created page edit screen. We still have the rest of the page greyed out during this time.

### CODE REVIEW

**Comment by briaguya** [comment]
@ifsimicoded Good catch on the spinner. I had forgotten that we already had an issue for that and was going at this in "bug fix" mode instead of looking for a well designed solution. I've talked to @amenity and we're moving forward with the fix including finishing up https://github.com/cityofaustin/techstack/issues/743

Also, would you like to take a stab and breaking up the bootstrap/react combo weirdness or should I?

**Comment by ifsimicoded** [comment]
Nice! If you’ve got bandwidth, do it!!!

**Comment by briaguya** [comment]
@ifsimicoded I'll hop on it!

**Comment by briaguya** [comment]
Hey @ifsimicoded I've addressed everything you mentioned:
gif of it

**Pull request merged**
