### PR TITLE
4695 Automate Translation Report sending

### PR DESCRIPTION
**Pull request by Niicck**
https://github.com/cityofaustin/techstack/issues/4695

coa-joplin-clean-up PR: https://github.com/cityofaustin/coa-joplin-clean-up/pull/2

# Description
We have a report that gets sent to Gabi, Inara, and Jair of all the pages that have been published in Joplin. It was MVP complete previously. Now, it's automated. It will create the report and send it directly to those teammates.

Screen Shot 2020-08-13 at 6 35 15 PM

The recipients of the translation report will be any team member that is part of the "Translators" group in Joplin. That way, no emails have to be hardcoded into the process.

The emails will be triggered by a coa-joplin-clean-up lambda function: https://github.com/cityofaustin/coa-joplin-clean-up/pull/2

# Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How can this be tested?
https://joplin-pr-4695-email.herokuapp.com/admin/users/
Add yourself to the "Translators" within the PR. And on Monday morning, you'll receive an email containing all the changes that have been made in Joplin.

# Checklist:
- [ ] Request reviewers
- [ ] Slack-out message for review
- [ ] Link this PR in the issue
- [ ] Moved card to *review* in zenhub

### CODE REVIEW

**Comment by chiaberry** [comment]
Reading the docs for the heroku scheduler it says, _"To schedule a frequency and time for a job, open the Scheduler dashboard by finding the app in My Apps, clicking “General Info”, then selecting “Scheduler” from the Add-ons drop down. "_

But I cannot find that drop down at all. Did you schedule the job via the command line? or am I blind and cant find it?

**Comment by Niicck** [comment]
To find it, you've got to add it as a resource: https://dashboard.heroku.com/apps/joplin-pr-4695-email/resources and then click the little <> on the end.

But Heroku actually admits that the Scheduler is bad, inconsistent, and shouldn't be used in production. https://devcenter.heroku.com/articles/scheduler#alternatives-to-heroku-scheduler

So I'm going to see if my clean up lambda can execute python code remotely: https://github.com/cityofaustin/coa-joplin-clean-up/blob/master/main.py

**Comment by chiaberry** [comment]
Oh I was looking for it on joplin! And not the PR app

**Comment by robbobfrh84** [comment]
Exciting. I'm all set. Can't wait for Monday!

**Comment by Niicck** [comment]
So we can use a lambda function to trigger it remotely. Cool. It's all ready for a Monday morning test. https://github.com/cityofaustin/coa-joplin-clean-up/pull/2/files

**Pull request merged**
